addons:
  apt:
    packages:
      - xvfb
language: node_js
env:
  - NODE_ENV=production
  - NODE_ENV=development
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - NODE_ENV=development npm install
script:
  - npm run test-with-coverage
